const JSON_HEADERS={"content-type":"application/json; charset=utf-8"};
function cors(origin,env){const allowed=String(env.ALLOWED_ORIGINS||"").split(",").map(x=>x.trim()).filter(Boolean);const ok=!allowed.length||allowed.includes(origin);return {"Access-Control-Allow-Origin":ok?origin:(allowed[0]||"*"),"Access-Control-Allow-Methods":"GET,PUT,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type,X-SnackOS-Key","Access-Control-Max-Age":"86400","Vary":"Origin"}}
function out(data,status,origin,env){return new Response(data===null?null:JSON.stringify(data),{status,headers:{...JSON_HEADERS,...cors(origin,env)}})}
function auth(req,env){return !env.SYNC_API_KEY||req.headers.get("X-SnackOS-Key")===env.SYNC_API_KEY}
export default {async fetch(req,env){const origin=req.headers.get("Origin")||"";if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin,env)});if(!auth(req,env))return out({error:"Unauthorized"},401,origin,env);const url=new URL(req.url);try{
 if(url.pathname==="/"||url.pathname==="/health")return out({ok:true,service:"SnackOS Shared Brain",time:new Date().toISOString()},200,origin,env);
 if(url.pathname==="/v1/state"&&req.method==="GET"){const {results}=await env.DB.prepare("SELECT state_key,value_json,updated_at,updated_by FROM app_state ORDER BY state_key").all();const states={};for(const r of results)states[r.state_key]={value:JSON.parse(r.value_json),updatedAt:r.updated_at,updatedBy:r.updated_by};return out({states,serverTime:new Date().toISOString()},200,origin,env)}
 const m=url.pathname.match(/^\/v1\/state\/([^/]+)$/);if(m&&req.method==="PUT"){const key=decodeURIComponent(m[1]);const body=await req.json();const now=new Date().toISOString();await env.DB.prepare(`INSERT INTO app_state(state_key,value_json,updated_at,updated_by) VALUES(?,?,?,?) ON CONFLICT(state_key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at,updated_by=excluded.updated_by`).bind(key,JSON.stringify(body.value??{}),now,String(body.device||"SnackOS")).run();await env.DB.prepare("INSERT INTO activity_log(action,state_key,detail,created_at) VALUES(?,?,?,?)").bind("state_updated",key,String(body.device||"SnackOS"),now).run();return out({ok:true,key,updatedAt:now},200,origin,env)}
 if(url.pathname==="/v1/activity"&&req.method==="GET"){const {results}=await env.DB.prepare("SELECT id,action,state_key,detail,created_at FROM activity_log ORDER BY id DESC LIMIT 100").all();return out({activity:results},200,origin,env)}
 return out({error:"Not found"},404,origin,env)
 }catch(e){return out({error:"Server error",message:String(e?.message||e)},500,origin,env)}}};